# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Course.create(requal_interval: 12, name: "Abrasive Blasting")
Course.create(requal_interval: 12, name: "Aerial Lifts")
Course.create(requal_interval: 12, name: "Asbestos Awareness")
Course.create(requal_interval: 12, name: "GFCI")
Course.create(requal_interval: 12, name: "Behavior Based Safety")
Course.create(requal_interval: 12, name: "Benzene Awareness")
Course.create(requal_interval: 12, name: "Bloodborne Pathogens")
Course.create(requal_interval: 12, name: "Confined Space / Permit Confined Space")
Course.create(requal_interval: 12, name: "Cranes")
Course.create(requal_interval: 12, name: "Disciplinary Program")
Course.create(requal_interval: 12, name: "Driving Safety")
Course.create(requal_interval: 12, name: "Electrical Safety Awareness")
Course.create(requal_interval: 12, name: "Fall Protection")
Course.create(requal_interval: 12, name: "Fatigue Management")
Course.create(requal_interval: 12, name: "Fire Protection / Extinguishers")
Course.create(requal_interval: 12, name: "First Aid")
Course.create(requal_interval: 12, name: "Forklift & Industrial Trucks")
Course.create(requal_interval: 12, name: "Gas Hazards")
Course.create(requal_interval: 12, name: "General Waste Management")
Course.create(requal_interval: 12, name: "Hand AND/OR Power Tools")
Course.create(requal_interval: 12, name: "Hazard Communication - (HAZCOM)")
Course.create(requal_interval: 12, name: "Hazard Identification & Risk Assessment")
Course.create(requal_interval: 12, name: "Hazardous Waste Operations / Emergency Response")
Course.create(requal_interval: 12, name: "Hydrogen Sulfide - H2S")
Course.create(requal_interval: 12, name: "In Plant Rail Safety")
Course.create(requal_interval: 12, name: "Incident Investigation and Reporting")
Course.create(requal_interval: 12, name: "Ladder Safety")
Course.create(requal_interval: 12, name: "Lead")
Course.create(requal_interval: 12, name: "Lead Awareness")
Course.create(requal_interval: 12, name: "Lockout / Tagout")
Course.create(requal_interval: 12, name: "Manual Lifting")
Course.create(requal_interval: 12, name: "Mobile Equipment")
Course.create(requal_interval: 12, name: "Natural Occurring Radioactive Material - (NORM)")
Course.create(requal_interval: 12, name: "Noise Awareness")
Course.create(requal_interval: 12, name: "Noise Exposure / Hearing Conservation")
Course.create(requal_interval: 12, name: "Personal Protective Equipment / Assessments - (PPE)")
Course.create(requal_interval: 12, name: "Respiratory Protection")
Course.create(requal_interval: 12, name: "Rigging Material Handling")
Course.create(requal_interval: 12, name: "Scaffolds")
Course.create(requal_interval: 12, name: "Short Service Employee (SSE)")
Course.create(requal_interval: 12, name: "Spill Prevention / Response")
Course.create(requal_interval: 12, name: "Stop Work Authority")
Course.create(requal_interval: 12, name: "Subcontractor Management Plan")
Course.create(requal_interval: 12, name: "Trenching / Shoring / Excavations")
Course.create(requal_interval: 12, name: "Welding - Cutting - Hot Work")
Course.create(requal_interval: 12, name: "Working Alone")

Client.create(name: "Boots Smith Oilfield Services LLC")

Group.create(name: "Pipeline")
Group.create(name: "Construction")

User.create(first_name: "Boots", last_name: "Smith", client_id: 1, group_id: 1)

Record.create(course_id: 1, user_id: 1, pass: true, score: 100, completed_date: '2009/04/13', requal_date: '2010/04/13')
Record.create(course_id: 2, user_id: 1, pass: true, score: 100, completed_date: '2009/03/23', requal_date: '2010/03/23')
Record.create(course_id: 3, user_id: 1, pass: true, score: 100, completed_date: '2009/03/23', requal_date: '2010/03/23')
Record.create(course_id: 4, user_id: 1, pass: true, score: 100, completed_date: '2009/05/18', requal_date: '2010/05/18')
Record.create(course_id: 5, user_id: 1, pass: true, score: 100, completed_date: '2011/03/23', requal_date: '2012/03/23')
Record.create(course_id: 6, user_id: 1, pass: true, score: 100, completed_date: '2009/05/11', requal_date: '2010/05/11')
Record.create(course_id: 7, user_id: 1, pass: true, score: 100, completed_date: '2009/03/02', requal_date: '2010/03/02')
Record.create(course_id: 8, user_id: 1, pass: true, score: 100, completed_date: '2009/05/25', requal_date: '2010/05/25')
Record.create(course_id: 9, user_id: 1, pass: true, score: 100, completed_date: '2009/05/04', requal_date: '2010/05/04')
Record.create(course_id: 10, user_id: 1, pass: true, score: 100, completed_date: '2013/03/03', requal_date: '2014/03/03')
Record.create(course_id: 11, user_id: 1, pass: true, score: 100, completed_date: '2010/05/11', requal_date: '2011/05/11')
Record.create(course_id: 12, user_id: 1, pass: true, score: 100, completed_date: '2009/03/09', requal_date: '2010/03/09')
Record.create(course_id: 13, user_id: 1, pass: true, score: 100, completed_date: '2009/03/16', requal_date: '2010/03/16')
Record.create(course_id: 14, user_id: 1, pass: true, score: 100, completed_date: '2011/04/13', requal_date: '2012/04/13')
Record.create(course_id: 15, user_id: 1, pass: true, score: 100, completed_date: '2009/03/02', requal_date: '2010/03/02')
Record.create(course_id: 16, user_id: 1, pass: true, score: 100, completed_date: '2009/06/07', requal_date: '2010/06/07')
Record.create(course_id: 17, user_id: 1, pass: true, score: 100, completed_date: '2011/03/16', requal_date: '2012/03/16')
Record.create(course_id: 18, user_id: 1, pass: true, score: 100, completed_date: '2011/04/16', requal_date: '2012/04/16')
Record.create(course_id: 19, user_id: 1, pass: true, score: 100, completed_date: '2011/04/20', requal_date: '2012/04/20')
Record.create(course_id: 20, user_id: 1, pass: true, score: 100, completed_date: '2009/03/09', requal_date: '2010/03/09')
Record.create(course_id: 21, user_id: 1, pass: true, score: 100, completed_date: '2009/01/26', requal_date: '2010/01/26')
Record.create(course_id: 22, user_id: 1, pass: true, score: 100, completed_date: '2011/05/18', requal_date: '2012/05/18')
Record.create(course_id: 23, user_id: 1, pass: true, score: 100, completed_date: '2011/05/14', requal_date: '2012/05/14')
Record.create(course_id: 24, user_id: 1, pass: true, score: 100, completed_date: '2009/06/07', requal_date: '2010/06/07')
Record.create(course_id: 25, user_id: 1, pass: true, score: 100, completed_date: '2011/04/27', requal_date: '2012/04/27')
Record.create(course_id: 26, user_id: 1, pass: true, score: 100, completed_date: '2011/03/30', requal_date: '2012/03/30')
Record.create(course_id: 27, user_id: 1, pass: true, score: 100, completed_date: '2009/01/12', requal_date: '2010/01/12')
Record.create(course_id: 28, user_id: 1, pass: true, score: 100, completed_date: '2009/01/19', requal_date: '2010/01/19')
Record.create(course_id: 29, user_id: 1, pass: true, score: 100, completed_date: '2001/01/19', requal_date: '2002/01/19')
Record.create(course_id: 30, user_id: 1, pass: true, score: 100, completed_date: '2009/06/14', requal_date: '2010/06/14')
Record.create(course_id: 31, user_id: 1, pass: true, score: 100, completed_date: '2001/03/30', requal_date: '2002/03/30')
Record.create(course_id: 32, user_id: 1, pass: true, score: 100, completed_date: '2011/05/18', requal_date: '2012/05/18')
Record.create(course_id: 33, user_id: 1, pass: true, score: 100, completed_date: '2011/03/30', requal_date: '2012/03/30')
Record.create(course_id: 34, user_id: 1, pass: true, score: 100, completed_date: '2010/06/14', requal_date: '2011/06/14')
Record.create(course_id: 35, user_id: 1, pass: true, score: 100, completed_date: '2009/03/30', requal_date: '2010/03/30')
Record.create(course_id: 36, user_id: 1, pass: true, score: 100, completed_date: '2009/04/27', requal_date: '2010/04/27')
Record.create(course_id: 37, user_id: 1, pass: true, score: 100, completed_date: '2009/05/18', requal_date: '2010/05/18')
Record.create(course_id: 38, user_id: 1, pass: true, score: 100, completed_date: '2009/04/20', requal_date: '2010/04/20')
Record.create(course_id: 39, user_id: 1, pass: true, score: 100, completed_date: '2009/04/06', requal_date: '2010/04/06')
Record.create(course_id: 40, user_id: 1, pass: true, score: 100, completed_date: '2011/01/12', requal_date: '2012/01/12')
Record.create(course_id: 41, user_id: 1, pass: true, score: 100, completed_date: '2011/06/07', requal_date: '2012/06/07')
Record.create(course_id: 42, user_id: 1, pass: true, score: 100, completed_date: '2011/01/26', requal_date: '2012/01/26')
Record.create(course_id: 43, user_id: 1, pass: true, score: 100, completed_date: '2011/05/18', requal_date: '2012/05/18')
Record.create(course_id: 44, user_id: 1, pass: true, score: 100, completed_date: '2009/03/16', requal_date: '2010/03/16')
Record.create(course_id: 45, user_id: 1, pass: true, score: 100, completed_date: '2009/05/11', requal_date: '2010/05/11')
Record.create(course_id: 46, user_id: 1, pass: true, score: 100, completed_date: '2011/03/09', requal_date: '2012/03/09')



# Seed Roster
User.create(first_name: 'AURELIO', last_name: 'CASTILLO', client_id: 1, group_id: 1)
User.create(first_name: 'ANDRES', last_name: 'RODRIGUEZ', client_id: 1, group_id: 1)
User.create(first_name: 'DERYL', last_name: 'HADLEY', client_id: 1, group_id: 1)
User.create(first_name: 'ALEJANDRO', last_name: 'ISLAS', client_id: 1, group_id: 1)
User.create(first_name: 'EDILBERTO', last_name: 'VARGAS', client_id: 1, group_id: 1)
User.create(first_name: 'ANGEL', last_name: 'CHAVEZ', client_id: 1, group_id: 1)
User.create(first_name: 'VIRGILIO', last_name: 'SANDOVAL', client_id: 1, group_id: 1)
User.create(first_name: 'BILLY', last_name: 'BREAUX', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'ROE', client_id: 1, group_id: 1)
User.create(first_name: 'ISABEL', last_name: 'GUZMAN-MELENDEZ', client_id: 1, group_id: 1)
User.create(first_name: 'HUGH', last_name: 'WATSON JR', client_id: 1, group_id: 1)
User.create(first_name: 'SABINO', last_name: 'MORALES', client_id: 1, group_id: 1)
User.create(first_name: 'BRADLEY', last_name: 'GRIENER', client_id: 1, group_id: 1)
User.create(first_name: 'ROCKY', last_name: 'TACKETT', client_id: 1, group_id: 1)
User.create(first_name: 'ROGELIO', last_name: 'VELA', client_id: 1, group_id: 1)
User.create(first_name: 'LANDON', last_name: 'MUHLBAUER', client_id: 1, group_id: 1)
User.create(first_name: 'ROEL', last_name: 'GAZCA', client_id: 1, group_id: 1)
User.create(first_name: 'JAMES', last_name: 'WEBB', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'EAKES', client_id: 1, group_id: 1)
User.create(first_name: 'FELIPE', last_name: 'HERNANDEZ', client_id: 1, group_id: 1)
User.create(first_name: 'SHANE', last_name: 'LAMBETH', client_id: 1, group_id: 1)
User.create(first_name: 'CHARLES', last_name: 'GREEN', client_id: 1, group_id: 1)
User.create(first_name: 'SAMUEL', last_name: 'GONZALES', client_id: 1, group_id: 1)
User.create(first_name: 'FELIX', last_name: 'MARTINEZ-PEREZ', client_id: 1, group_id: 1)
User.create(first_name: 'BOBBY', last_name: 'COLE', client_id: 1, group_id: 1)
User.create(first_name: 'ROBERT', last_name: 'RILEY', client_id: 1, group_id: 1)
User.create(first_name: 'ROBBIE', last_name: 'BOYETTE', client_id: 1, group_id: 1)
User.create(first_name: 'BENNIE', last_name: 'WALKER', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'RODRIGUEZ', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'MCILWAIN', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'SHINGLER', client_id: 1, group_id: 1)
User.create(first_name: 'JERRY', last_name: 'COLEMAN', client_id: 1, group_id: 1)
User.create(first_name: 'HUBERT', last_name: 'ANDERSON JR', client_id: 1, group_id: 1)
User.create(first_name: 'OSCAR', last_name: 'DE LA CRUZ', client_id: 1, group_id: 1)
User.create(first_name: 'MARK', last_name: 'PHELPS', client_id: 1, group_id: 1)
User.create(first_name: 'JOHN', last_name: 'MCILWAIN', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'DINO', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'DUBOSE', client_id: 1, group_id: 1)
User.create(first_name: 'BOBBI', last_name: 'LAUNEY', client_id: 1, group_id: 1)
User.create(first_name: 'JUSTIN', last_name: 'WOOD', client_id: 1, group_id: 1)
User.create(first_name: 'DOUGLAS', last_name: 'BISHOP', client_id: 1, group_id: 1)
User.create(first_name: 'ALAN', last_name: 'MORALES', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'FLORES JR', client_id: 1, group_id: 1)
User.create(first_name: 'ROLANDO', last_name: 'GUZMAN', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'MASCORRO', client_id: 1, group_id: 1)
User.create(first_name: 'JERRY', last_name: 'BELL', client_id: 1, group_id: 1)
User.create(first_name: 'BARRY', last_name: 'LOPER', client_id: 1, group_id: 1)
User.create(first_name: 'DANIEL', last_name: 'CHAVERS', client_id: 1, group_id: 1)
User.create(first_name: 'REYNALDO', last_name: 'RODRIGUEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JESUS', last_name: 'SALGADO', client_id: 1, group_id: 1)
User.create(first_name: 'JUSTIN', last_name: 'GREGORY', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'CROCKER', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'LOPEZ', client_id: 1, group_id: 1)
User.create(first_name: 'CURTIS', last_name: 'MOYE', client_id: 1, group_id: 1)
User.create(first_name: 'THOMAS', last_name: 'STACEY', client_id: 1, group_id: 1)
User.create(first_name: 'BRIAN', last_name: 'JONES', client_id: 1, group_id: 1)
User.create(first_name: 'PAMELA', last_name: 'ALLEN', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'MORGAN', client_id: 1, group_id: 1)
User.create(first_name: 'GERARDO', last_name: 'PADILLA', client_id: 1, group_id: 1)
User.create(first_name: 'RONALD', last_name: 'CROCKER', client_id: 1, group_id: 1)
User.create(first_name: 'FRANK', last_name: 'RASH JR', client_id: 1, group_id: 1)
User.create(first_name: 'FRANKLIN', last_name: 'MCCAUGHN', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'MORGAN', client_id: 1, group_id: 1)
User.create(first_name: 'BILLY', last_name: 'ELLINGBURG', client_id: 1, group_id: 1)
User.create(first_name: 'ROCHELLE', last_name: 'CLARK', client_id: 1, group_id: 1)
User.create(first_name: 'REGINALD', last_name: 'CARTER', client_id: 1, group_id: 1)
User.create(first_name: 'STEVEN', last_name: 'PISUT', client_id: 1, group_id: 1)
User.create(first_name: 'MIGUEL', last_name: 'ROSAS', client_id: 1, group_id: 1)
User.create(first_name: 'RAUL', last_name: 'CASTILLO', client_id: 1, group_id: 1)
User.create(first_name: 'EUGENE', last_name: 'SMITH', client_id: 1, group_id: 1)
User.create(first_name: 'DEREK', last_name: 'ANDERSON', client_id: 1, group_id: 1)
User.create(first_name: 'MANUEL', last_name: 'RICO', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'BOUT', client_id: 1, group_id: 1)
User.create(first_name: 'RANDY', last_name: 'WRIGHT', client_id: 1, group_id: 1)
User.create(first_name: 'RYAN', last_name: 'BOWDIN', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'LOPEZ', client_id: 1, group_id: 1)
User.create(first_name: 'DANCEY', last_name: 'MCCOOL', client_id: 1, group_id: 1)
User.create(first_name: 'DONALD', last_name: 'PLAKE', client_id: 1, group_id: 1)
User.create(first_name: 'DURL', last_name: 'LEBOEUF', client_id: 1, group_id: 1)
User.create(first_name: 'RICKY', last_name: 'SMITH', client_id: 1, group_id: 1)
User.create(first_name: 'FELIPE', last_name: 'NAJERA', client_id: 1, group_id: 1)
User.create(first_name: 'LUKE', last_name: 'PARKER', client_id: 1, group_id: 1)
User.create(first_name: 'TOMMY', last_name: 'RUSHING', client_id: 1, group_id: 1)
User.create(first_name: 'KERRY', last_name: 'VICKNAIR', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'ANDERSON', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'HOWELL', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'JONES', client_id: 1, group_id: 1)
User.create(first_name: 'CHARLES', last_name: 'PITTMAN', client_id: 1, group_id: 1)
User.create(first_name: 'RAYMOND', last_name: 'HAYS', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'MASCORRO', client_id: 1, group_id: 1)
User.create(first_name: 'RANDELL', last_name: 'CROCKER', client_id: 1, group_id: 1)
User.create(first_name: 'BRUCE', last_name: 'GALLOWAY', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTIAN', last_name: 'SALGADO', client_id: 1, group_id: 1)
User.create(first_name: 'EFRAIN', last_name: 'MARTINEZ', client_id: 1, group_id: 1)
User.create(first_name: 'SHELLIE', last_name: 'COX', client_id: 1, group_id: 1)
User.create(first_name: 'RANDY', last_name: 'GRAYSON JR', client_id: 1, group_id: 1)
User.create(first_name: 'RUTH', last_name: 'ELLINGBURG', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'TRAHAN', client_id: 1, group_id: 1)
User.create(first_name: 'MIGUEL', last_name: 'CASTILLO', client_id: 1, group_id: 1)
User.create(first_name: 'SPENSER', last_name: 'BERTRAND', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'YATES', client_id: 1, group_id: 1)
User.create(first_name: 'MONSERRATO', last_name: 'CASTILLO-AGUILAR', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'BURTON', client_id: 1, group_id: 1)
User.create(first_name: 'HOWARD', last_name: 'HANCOCK', client_id: 1, group_id: 1)
User.create(first_name: 'JEROME', last_name: 'BLANCHARD', client_id: 1, group_id: 1)
User.create(first_name: 'GLEENWELL', last_name: 'JOHNSON', client_id: 1, group_id: 1)
User.create(first_name: 'DAVID', last_name: 'STALLINGS', client_id: 1, group_id: 1)
User.create(first_name: 'MITCHELL', last_name: 'SCHEXNIDER', client_id: 1, group_id: 1)
User.create(first_name: 'ADAM', last_name: 'COTTEN', client_id: 1, group_id: 1)
User.create(first_name: 'BEN', last_name: 'WALKER', client_id: 1, group_id: 1)
User.create(first_name: 'AUSTIN', last_name: 'TAYLOR', client_id: 1, group_id: 1)
User.create(first_name: 'TERRY', last_name: 'ELLIOTT', client_id: 1, group_id: 1)
User.create(first_name: 'BRUCE', last_name: 'GRADDY', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'CONTRERAS', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'GARCIA', client_id: 1, group_id: 1)
User.create(first_name: 'TOMAS', last_name: 'LOPEZ-CHINAS', client_id: 1, group_id: 1)
User.create(first_name: 'SCOTTIE', last_name: 'MITCHELL', client_id: 1, group_id: 1)
User.create(first_name: 'CORNELIUS', last_name: 'ARDENEAUX JR', client_id: 1, group_id: 1)
User.create(first_name: 'ROBERT', last_name: 'NESTER', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'DAVIDSON', client_id: 1, group_id: 1)
User.create(first_name: 'STEVEN', last_name: 'DELLARIA', client_id: 1, group_id: 1)
User.create(first_name: 'MIGUEL', last_name: 'TORRES', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'VARGAS', client_id: 1, group_id: 1)
User.create(first_name: 'DONALD', last_name: 'ELLIS', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'WRIGHT', client_id: 1, group_id: 1)
User.create(first_name: 'ALAN', last_name: 'PALACIOS', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'SIMS', client_id: 1, group_id: 1)
User.create(first_name: 'RICARDO', last_name: 'LOPEZ', client_id: 1, group_id: 1)
User.create(first_name: 'EARNEST', last_name: 'COON', client_id: 1, group_id: 1)
User.create(first_name: 'JOSEPH', last_name: 'BAILEY', client_id: 1, group_id: 1)
User.create(first_name: 'SCOTT', last_name: 'MCDERMOTT', client_id: 1, group_id: 1)
User.create(first_name: 'GEORGE', last_name: 'WILSON JR', client_id: 1, group_id: 1)
User.create(first_name: 'ADRIAN', last_name: 'SANCHEZ', client_id: 1, group_id: 1)
User.create(first_name: 'BRADON', last_name: 'SKAINS', client_id: 1, group_id: 1)
User.create(first_name: 'JOEY', last_name: 'SKAINS', client_id: 1, group_id: 1)
User.create(first_name: 'JONATHAN', last_name: 'BISHOP', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'CROCKER', client_id: 1, group_id: 1)
User.create(first_name: 'TERRY', last_name: 'VANCE', client_id: 1, group_id: 1)
User.create(first_name: 'FRANK', last_name: 'FRANCIS', client_id: 1, group_id: 1)
User.create(first_name: 'BIBIANO', last_name: 'BALLEZA JR', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'TAYLOR', client_id: 1, group_id: 1)
User.create(first_name: 'VERNON', last_name: 'BELL', client_id: 1, group_id: 1)
User.create(first_name: 'MARK', last_name: 'BONDURANT', client_id: 1, group_id: 1)
User.create(first_name: 'TIMOTHY', last_name: 'EDWARDS', client_id: 1, group_id: 1)
User.create(first_name: 'JUSTIN', last_name: 'HOLLINGSWORTH', client_id: 1, group_id: 1)
User.create(first_name: 'MICKEL', last_name: 'SMITH JR', client_id: 1, group_id: 1)
User.create(first_name: 'JULIAN', last_name: 'GONZALEZ', client_id: 1, group_id: 1)
User.create(first_name: 'GERALD', last_name: 'TRAHAN', client_id: 1, group_id: 1)
User.create(first_name: 'EUGENE', last_name: 'BILLEAUD', client_id: 1, group_id: 1)
User.create(first_name: 'JUAN', last_name: 'GONZALEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'MORALES', client_id: 1, group_id: 1)
User.create(first_name: 'MATTHEW', last_name: 'MCGEE', client_id: 1, group_id: 1)
User.create(first_name: 'JAVIER', last_name: 'GONZALEZ', client_id: 1, group_id: 1)
User.create(first_name: 'ANDREW', last_name: 'WESTBROOK', client_id: 1, group_id: 1)
User.create(first_name: 'TONY', last_name: 'HAMMONDS', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'HAYES', client_id: 1, group_id: 1)
User.create(first_name: 'JOHN', last_name: 'WALL', client_id: 1, group_id: 1)
User.create(first_name: 'EDDIE', last_name: 'MCMULLAN', client_id: 1, group_id: 1)
User.create(first_name: 'MATTHEW', last_name: 'CHURCH', client_id: 1, group_id: 1)
User.create(first_name: 'CORTNI', last_name: 'GIBSON', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'WALDO', client_id: 1, group_id: 1)
User.create(first_name: 'JAMES', last_name: 'GYLES', client_id: 1, group_id: 1)
User.create(first_name: 'JUSTIN', last_name: 'BOUTTE', client_id: 1, group_id: 1)
User.create(first_name: 'ORLANDO', last_name: 'SANCHEZ-ROSALES', client_id: 1, group_id: 1)
User.create(first_name: 'MILES', last_name: 'PUSATERI', client_id: 1, group_id: 1)
User.create(first_name: 'FREEMAN', last_name: 'MCDOWELL', client_id: 1, group_id: 1)
User.create(first_name: 'ANTHONY', last_name: 'ORTEGA', client_id: 1, group_id: 1)
User.create(first_name: 'ANDRE', last_name: 'BILLEAUD', client_id: 1, group_id: 1)
User.create(first_name: 'JACQUE', last_name: 'BILLEAUD', client_id: 1, group_id: 1)
User.create(first_name: 'TYE', last_name: 'MARICLE', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'CASTILLO', client_id: 1, group_id: 1)
User.create(first_name: 'EDGAR', last_name: 'MACIAS', client_id: 1, group_id: 1)
User.create(first_name: 'LEONARDO', last_name: 'HERNANDEZ', client_id: 1, group_id: 1)
User.create(first_name: 'PAUL', last_name: 'KINSEY', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'DUNCAN', client_id: 1, group_id: 1)
User.create(first_name: 'AGUSTIN', last_name: 'CASTILLO', client_id: 1, group_id: 1)
User.create(first_name: 'PEDRO', last_name: 'DINO', client_id: 1, group_id: 1)
User.create(first_name: 'BRADLEY', last_name: 'MAGLIOLO', client_id: 1, group_id: 1)
User.create(first_name: 'ROMEO', last_name: 'VELA', client_id: 1, group_id: 1)
User.create(first_name: 'KANDICE', last_name: 'ROBERSON', client_id: 1, group_id: 1)
User.create(first_name: 'KENNETH', last_name: 'KLINE', client_id: 1, group_id: 1)
User.create(first_name: 'RICHARD', last_name: 'COLEMAN', client_id: 1, group_id: 1)
User.create(first_name: 'BILLY', last_name: 'MCILWAIN', client_id: 1, group_id: 1)
User.create(first_name: 'RANDAL', last_name: 'WEARREN', client_id: 1, group_id: 1)
User.create(first_name: 'ETHAN', last_name: 'PELTIER', client_id: 1, group_id: 1)
User.create(first_name: 'JOHN', last_name: 'DOGA', client_id: 1, group_id: 1)
User.create(first_name: 'CASEY', last_name: 'BURNS', client_id: 1, group_id: 1)
User.create(first_name: 'CRUZ', last_name: 'ORTEGA', client_id: 1, group_id: 1)
User.create(first_name: 'DULCIE', last_name: 'DIXON', client_id: 1, group_id: 1)
User.create(first_name: 'ROBERT', last_name: 'ELLIOTT', client_id: 1, group_id: 1)
User.create(first_name: 'RICHARD', last_name: 'TIDWELL', client_id: 1, group_id: 1)
User.create(first_name: 'LONNIE', last_name: 'CHIPLEY', client_id: 1, group_id: 1)
User.create(first_name: 'JOHN', last_name: 'COLEMAN', client_id: 1, group_id: 1)
User.create(first_name: 'HECTOR', last_name: 'HERNANDEZ-SANCHEZ', client_id: 1, group_id: 1)
User.create(first_name: 'PATRICK', last_name: 'MILLER', client_id: 1, group_id: 1)
User.create(first_name: 'JUAN', last_name: 'CHAGOYA', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'TORRES-OBREGON', client_id: 1, group_id: 1)
User.create(first_name: 'JULIO', last_name: 'GALLEGOS', client_id: 1, group_id: 1)
User.create(first_name: 'MICAH', last_name: 'MARKS', client_id: 1, group_id: 1)
User.create(first_name: 'LARRY', last_name: 'PITTMAN', client_id: 1, group_id: 1)
User.create(first_name: 'MARSHA', last_name: 'MILLER', client_id: 1, group_id: 1)
User.create(first_name: 'MARVIN', last_name: 'VARNADO', client_id: 1, group_id: 1)
User.create(first_name: 'DAN', last_name: 'WALKER', client_id: 1, group_id: 1)
User.create(first_name: 'O C', last_name: 'TATE', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'IBARRA', client_id: 1, group_id: 1)
User.create(first_name: 'PATRICIO', last_name: 'PADRON', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'LOPEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JULIAN', last_name: 'GUTIERREZ', client_id: 1, group_id: 1)
User.create(first_name: 'ARTURO', last_name: 'GASCA', client_id: 1, group_id: 1)
User.create(first_name: 'DONACIANO', last_name: 'GARCIA-REYES', client_id: 1, group_id: 1)
User.create(first_name: 'STONEY', last_name: 'PARKER', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'BRESE', client_id: 1, group_id: 1)
User.create(first_name: 'SHARON', last_name: 'BOOTHE', client_id: 1, group_id: 1)
User.create(first_name: 'JAKUS', last_name: 'LEE', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'KIGHT', client_id: 1, group_id: 1)
User.create(first_name: 'CODY', last_name: 'PEBWORTH', client_id: 1, group_id: 1)
User.create(first_name: 'SCOTT', last_name: 'WEBER', client_id: 1, group_id: 1)
User.create(first_name: 'RAYMOND', last_name: 'WARREN', client_id: 1, group_id: 1)
User.create(first_name: 'BRANDON', last_name: 'MORRISON', client_id: 1, group_id: 1)
User.create(first_name: 'JACKSON', last_name: 'WARD', client_id: 1, group_id: 1)
User.create(first_name: 'ROGELIO', last_name: 'GONZALEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JAMES', last_name: 'WASHBURN', client_id: 1, group_id: 1)
User.create(first_name: 'MARK', last_name: 'CASTILLE', client_id: 1, group_id: 1)
User.create(first_name: 'DARREL', last_name: 'DARTEZ', client_id: 1, group_id: 1)
User.create(first_name: 'COLTON', last_name: 'ARMSTRONG', client_id: 1, group_id: 1)
User.create(first_name: 'DWIGHT', last_name: 'BRASSEAUX', client_id: 1, group_id: 1)
User.create(first_name: 'RODERICK', last_name: 'ABSHIRE', client_id: 1, group_id: 1)
User.create(first_name: 'HECTOR', last_name: 'GALVAN', client_id: 1, group_id: 1)
User.create(first_name: 'SHELBY', last_name: 'NELSON', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'MCCLURE JR', client_id: 1, group_id: 1)
User.create(first_name: 'TAMMY', last_name: 'BRIGGS-NELSON', client_id: 1, group_id: 1)
User.create(first_name: 'CHAD ', last_name: 'MOORE', client_id: 1, group_id: 1)
User.create(first_name: 'ROBERT', last_name: 'BEASLEY', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'GRACIANO', client_id: 1, group_id: 1)
User.create(first_name: 'CHRISTOPHER', last_name: 'TAYLOR', client_id: 1, group_id: 1)
User.create(first_name: 'SANDY', last_name: 'BRASSEAUX', client_id: 1, group_id: 1)
User.create(first_name: 'BONNIE', last_name: 'MAYNARD', client_id: 1, group_id: 1)
User.create(first_name: 'STACEY', last_name: 'LARY', client_id: 1, group_id: 1)
User.create(first_name: 'ANTHONY', last_name: 'CLUFF', client_id: 1, group_id: 1)
User.create(first_name: 'DAMON', last_name: 'MARICLE', client_id: 1, group_id: 1)
User.create(first_name: 'LORENZO', last_name: 'MENDOZA', client_id: 1, group_id: 1)
User.create(first_name: 'ALFRED', last_name: 'PIERCE', client_id: 1, group_id: 1)
User.create(first_name: 'CRAIG', last_name: 'TAYLOR', client_id: 1, group_id: 1)
User.create(first_name: 'STEVEN', last_name: 'HOGG', client_id: 1, group_id: 1)
User.create(first_name: 'LANNY', last_name: 'HEDGECOCK', client_id: 1, group_id: 1)
User.create(first_name: 'TYLER', last_name: 'STROTHER', client_id: 1, group_id: 1)
User.create(first_name: 'AARON', last_name: 'SASSER', client_id: 1, group_id: 1)
User.create(first_name: 'BRYAN', last_name: 'SNELL', client_id: 1, group_id: 1)
User.create(first_name: 'ROGER', last_name: 'DENNISON', client_id: 1, group_id: 1)
User.create(first_name: 'KEVIN', last_name: 'DUCK', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'LEBLANC', client_id: 1, group_id: 1)
User.create(first_name: 'RICKY', last_name: 'NELSON', client_id: 1, group_id: 1)
User.create(first_name: 'TAMMY', last_name: 'HEDGECOCK', client_id: 1, group_id: 1)
User.create(first_name: 'ETHAN', last_name: 'SMITH', client_id: 1, group_id: 1)
User.create(first_name: 'NICHOLIS', last_name: 'LEE', client_id: 1, group_id: 1)
User.create(first_name: 'AARON', last_name: 'TWIGG', client_id: 1, group_id: 1)
User.create(first_name: 'DIEGO', last_name: 'CHAPA', client_id: 1, group_id: 1)
User.create(first_name: 'MICHELLE', last_name: 'POWELL', client_id: 1, group_id: 1)
User.create(first_name: 'MIGUEL', last_name: 'BELTRAN', client_id: 1, group_id: 1)
User.create(first_name: 'ROGELIO', last_name: 'GOMEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JACOB', last_name: 'WALLACE', client_id: 1, group_id: 1)
User.create(first_name: 'ORNA', last_name: 'FRANKS', client_id: 1, group_id: 1)
User.create(first_name: 'ROBERT', last_name: 'MORRISON', client_id: 1, group_id: 1)
User.create(first_name: 'TONY', last_name: 'LEE', client_id: 1, group_id: 1)
User.create(first_name: 'JOSE', last_name: 'GUILLEN', client_id: 1, group_id: 1)
User.create(first_name: 'KADE', last_name: 'JANTZ', client_id: 1, group_id: 1)
User.create(first_name: 'CHADWICK', last_name: 'TODD', client_id: 1, group_id: 1)
User.create(first_name: 'WILLARD', last_name: 'FORSYTHE', client_id: 1, group_id: 1)
User.create(first_name: 'LEE', last_name: 'GUERRERO', client_id: 1, group_id: 1)
User.create(first_name: 'WESLEY', last_name: 'SAM', client_id: 1, group_id: 1)
User.create(first_name: 'DUSTIN', last_name: 'GRIGG', client_id: 1, group_id: 1)
User.create(first_name: 'LARRY', last_name: 'GABEHART', client_id: 1, group_id: 1)
User.create(first_name: 'WESLEY', last_name: 'PEBWORTH', client_id: 1, group_id: 1)
User.create(first_name: 'WALTON', last_name: 'GOLD', client_id: 1, group_id: 1)
User.create(first_name: 'OLEGARIO', last_name: 'CHAPA', client_id: 1, group_id: 1)
User.create(first_name: 'PATRICIA', last_name: 'SHELTON', client_id: 1, group_id: 1)
User.create(first_name: 'BRANDON', last_name: 'NELSON', client_id: 1, group_id: 1)
User.create(first_name: 'CASEY', last_name: 'BOYETT', client_id: 1, group_id: 1)
User.create(first_name: 'LUIS', last_name: 'CANALES', client_id: 1, group_id: 1)
User.create(first_name: 'ERIC', last_name: 'TREVATHAN', client_id: 1, group_id: 1)
User.create(first_name: 'JULIAN', last_name: 'TREVATHAN', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'SHELTON', client_id: 1, group_id: 1)
User.create(first_name: 'DUSTIN', last_name: 'COLBERT', client_id: 1, group_id: 1)
User.create(first_name: 'ELLIOT', last_name: 'BRASSEAUX', client_id: 1, group_id: 1)
User.create(first_name: 'ADAM', last_name: 'COLE', client_id: 1, group_id: 1)
User.create(first_name: 'PAUL', last_name: 'COTRELL', client_id: 1, group_id: 1)
User.create(first_name: 'NATHANIEL', last_name: 'SMITH', client_id: 1, group_id: 1)
User.create(first_name: 'RUSSELL', last_name: 'SHELTON', client_id: 1, group_id: 1)
User.create(first_name: 'JOHN', last_name: 'CARRUTH', client_id: 1, group_id: 1)
User.create(first_name: 'DAELIN', last_name: 'BRASSEAUX', client_id: 1, group_id: 1)
User.create(first_name: 'MICHEAL', last_name: 'COATES', client_id: 1, group_id: 1)
User.create(first_name: 'DAKOTA', last_name: 'HEDGECOCK', client_id: 1, group_id: 1)
User.create(first_name: 'CODY', last_name: 'STACY', client_id: 1, group_id: 1)
User.create(first_name: 'LORON', last_name: 'DARLING', client_id: 1, group_id: 1)
User.create(first_name: 'ALBERT', last_name: 'MAYNARD', client_id: 1, group_id: 1)
User.create(first_name: 'MICHAEL', last_name: 'PATTEN', client_id: 1, group_id: 1)
User.create(first_name: 'JOHNATHAN', last_name: 'RUDROW', client_id: 1, group_id: 1)
User.create(first_name: 'JASON', last_name: 'PEBWORTH', client_id: 1, group_id: 1)
User.create(first_name: 'XITLALI', last_name: 'MENDOZA', client_id: 1, group_id: 1)
User.create(first_name: 'JESUS', last_name: 'MORALES', client_id: 1, group_id: 1)
User.create(first_name: 'TRANQUILINO', last_name: 'TORRES-HERNANDEZ', client_id: 1, group_id: 1)
User.create(first_name: 'MONICA', last_name: 'LEBLANC', client_id: 1, group_id: 1)
User.create(first_name: 'JOSHUA', last_name: 'CLARK', client_id: 1, group_id: 1)
User.create(first_name: 'IVAN', last_name: 'TORRES-REYNA', client_id: 1, group_id: 1)
User.create(first_name: 'ENRIQUE', last_name: 'HERNANDEZ', client_id: 1, group_id: 1)
User.create(first_name: 'JEFFREY', last_name: 'TODD', client_id: 1, group_id: 1)
User.create(first_name: 'KELLY', last_name: 'KNIGHTEN', client_id: 1, group_id: 1)
User.create(first_name: 'PEDRO', last_name: 'TORRES-REYNA', client_id: 1, group_id: 1)
User.create(first_name: 'DESTINY', last_name: 'DEROUEN', client_id: 1, group_id: 1)
User.create(first_name: 'WILLIAM', last_name: 'TUCKER', client_id: 1, group_id: 2)
User.create(first_name: 'EDDIE', last_name: 'CARMICHAEL', client_id: 1, group_id: 2)
User.create(first_name: 'JOHN', last_name: 'DAVIS', client_id: 1, group_id: 2)
User.create(first_name: 'TOM', last_name: 'SUMLING JR', client_id: 1, group_id: 2)
User.create(first_name: 'PATRICK', last_name: 'MCDONALD', client_id: 1, group_id: 2)
User.create(first_name: 'BOBBY', last_name: 'JONES', client_id: 1, group_id: 2)
User.create(first_name: 'MARCUS', last_name: 'COLEMAN', client_id: 1, group_id: 2)
User.create(first_name: 'JERRY', last_name: 'NOBLES', client_id: 1, group_id: 2)
User.create(first_name: 'CALVIN', last_name: 'ELLIS', client_id: 1, group_id: 2)
User.create(first_name: 'WILLIE', last_name: 'CARMICHAEL', client_id: 1, group_id: 2)
User.create(first_name: 'CHRISTOPHER', last_name: 'TANNER', client_id: 1, group_id: 2)
User.create(first_name: 'DEONDRICK', last_name: 'HARDY', client_id: 1, group_id: 2)
User.create(first_name: 'JOHN', last_name: 'LINDSEY', client_id: 1, group_id: 2)
User.create(first_name: 'LEE', last_name: 'CARMICHAEL', client_id: 1, group_id: 2)
User.create(first_name: 'JIMMY', last_name: 'CARMICHAEL', client_id: 1, group_id: 2)
User.create(first_name: 'BILLY', last_name: 'SUMRALL', client_id: 1, group_id: 2)
User.create(first_name: 'DONALD', last_name: 'CRAIG', client_id: 1, group_id: 2)
User.create(first_name: 'TROY', last_name: 'PEARSON', client_id: 1, group_id: 2)
User.create(first_name: 'DWIGHT', last_name: 'GRANTHAM', client_id: 1, group_id: 2)
User.create(first_name: 'ANTHONY', last_name: 'TURNER', client_id: 1, group_id: 2)
User.create(first_name: 'KELLY', last_name: 'SANDERSON', client_id: 1, group_id: 2)
User.create(first_name: 'ELKENDRICK', last_name: 'WATERS', client_id: 1, group_id: 2)
User.create(first_name: 'SHANNON', last_name: 'DICKERSON', client_id: 1, group_id: 2)
User.create(first_name: 'GEORGE', last_name: 'HARDAWAY', client_id: 1, group_id: 2)
User.create(first_name: 'TYSON', last_name: 'POWELL', client_id: 1, group_id: 2)
User.create(first_name: 'DION', last_name: 'MCLAIN', client_id: 1, group_id: 2)
User.create(first_name: 'MORRIS', last_name: 'ROBINSON', client_id: 1, group_id: 2)
User.create(first_name: 'PRENTISS', last_name: 'SIMPSON', client_id: 1, group_id: 2)
User.create(first_name: 'ROBERT', last_name: 'ARRINGTON', client_id: 1, group_id: 2)
User.create(first_name: 'VONDELL', last_name: 'SMITH', client_id: 1, group_id: 2)